# Generated by Django 6.0.4 on 2026-05-02 08:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_branch_company_alter_userprofile_role_instock_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('PENDING_DELETION', 'Pending Deletion'), ('PAUSED', 'Paused')], default='ACTIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='status_updated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
